#!/bin/bash
git fetch && \
    git checkout master && \
    git pull --all && \
    git submodule init && \
    git submodule update . &&\
    git submodule sync && \

_wd=`pwd`
for repo in `find ${_wd} -type f -name '.git' 2>/dev/null` ; do
    repo="${repo/.git/}"
    echo "---- repo="$repo
    cd ${repo}/
    git fetch
    git checkout master
    git pull --all
    git submodule init && git submodule update . && git submodule sync
done
cd ${_wd}

echo "--DONE--"
