#!/bin/bash
_lst=""
function look_cc_files {
  for e in `find . -type f -name "$*"` ; do _lst="$_lst $e" ; done
}
look_cc_files '*.c'
look_cc_files '*.cc'
look_cc_files '*.cpp'
look_cc_files '*.cxx'
look_cc_files '*.h'
look_cc_files '*.hh'
look_cc_files '*.hpp'
look_cc_files '*.hxx'

gcc -M $_lst | sed -e 's/[\\ ]/\n/g' | \
  sed -e '/^$/d' -e '/\.o:[ \t]*$/d' | \
  ctags -f .ctags -L - --c++-kinds=+p --fields=+iaS --extra=+q
