#!/bin/bash

function make_ctags_file_by_file {
  gcc -M $* | sed -e 's/[\\ ]/\n/g' | \
    sed -e '/^$/d' -e '/\.o:[ \t]*$/d' | \
      ctags -L - --c++-kinds=+p --fields=+iaS --extra=+q
}

if [ "$1" == "-r" ] || [ "$1" == '-R' ] ; then
  _dir="$2"
  if [ "${_dir}" != "" ] ; then _dir="`pwd`" ; fi
  ctags -R --c++-kinds=+p --fields=+iaS --extra=+q $_dir
else
  make_ctags_file_by_file $*
fi

if [ -f './tags' ] ; then mv ./tags .tags ; fi

